Km 5331 add container part to rux-container
RocketCommunicationsInc/astro pull request #1039
Opened 2023-01-24 21:08 UTC by kiley-mitti

## Brief Description

Added a 'container' part to the outermost div of the rux-container. I also added scrollbar stylings.

## JIRA Link

[ASTRO-5331](https://rocketcom.atlassian.net/browse/ASTRO-5331)

## Related Issue

## General Notes

## Motivation and Context

It was brought to our attention by @brikiernan that a very common use case for containers was to hold scrollable content. It was difficult to style the height of rux-container in such a way that would allow the inner parts to align properly and the body to scroll. Adding part='container' to the surrounding div should allow for more flexibility and easier access to change height properties/add Flexbox or grid stylings for layout.

## Issues and Limitations

## Types of changes

- [ ] Bug fix
- [x] New feature
- [ ] Breaking change

## Checklist

- [x] This PR changes a Storybook story.
- [ ] I have added tests to cover my changes.
- [x] Regressions are passing and/or failures are documented
- [x] Changes have been checked in evergreen browsers

2023-01-24 23:36 UTC, micahjones13 approved these changes

2023-01-25 15:04 UTC, markacianfrani requested changes
can you change the changeset to minor plz since we're adding a new part? the scroll styles would be patch but we can just roll it all in one. also, can you mark all the packages instead of just web-comps? if we only mark web comps, changesets won't bump the wrappers when we version.

2023-01-25 19:04 UTC, kiley-mitti commented
sure thing!

2023-01-26 13:50 UTC, markacianfrani approved these changes

2023-01-26 13:50 UTC, merged