Changed rux-select to use box-shadow rather than border
RocketCommunicationsInc/astro pull request #1191
Opened 2023-07-21 20:21 UTC by nortonprojects

## Brief Description

`rux-input` uses box-shadow, not border, which gives it a height of 36px by default. `rux-select` uses the opposite, which gives it a height of 38px by default. This makes aligning a `rux-select` and `rux-input` extremely frustrating.

This PR just changes `rux-select` to be consistent with `rux-input`, making the height the same and alignment trivial.

## Types of changes

- [X] Bug fix
- [ ] New feature
- [X??] Breaking change

## Checklist

- [ ] This PR adds or removes a Storybook story.
- [ ] I have added tests to cover my changes.
- [ ] Regressions are passing and/or failures are documented
- [ ] Changes have been checked in evergreen browsers

2023-07-24 16:54 UTC, markacianfrani requested changes
Visual regression tests failing for a number of other variants:

* light mode - invalid
* inline - default/hover
* invalid + disabled

basically find/replace all other instances of `border:` and change them to box-shadow.
if you run `npm run test.server` (with dev server running), you can see every variant laid out at 

http://localhost:3334/src/components/rux-select/test/basic/
http://localhost:3334/src/components/rux-select/test/inline/

2023-07-28 19:33 UTC, markacianfrani commented
https://rocketcom.atlassian.net/browse/ASTRO-6492

2023-08-09 15:24 UTC, kiley-mitti commented
@nortonprojects I've solved this and merged it it will be available in the next minor patch! Thanks for pointing it out! :)

2023-08-09 15:24 UTC, closed without merging

2023-08-09 15:24 UTC, kiley-mitti reviewed
changed in a different branch