fix(switch): Fix label prop on Switch component not working in Storyb…
RocketCommunicationsInc/astro pull request #202
Opened 2022-01-18 19:45 UTC by thomasneal

## Brief Description

Fixed Switch component's label not rendering correct in Storybook canvas

## JIRA Link

[(https://rocketcom.atlassian.net/browse/ASTRO-2772)]

## Related Issue

## General Notes

## Motivation and Context

Currently broken on live site so needs to be completed for best experience for users

## Issues and Limitations

## Types of changes

- [X] Bug fix
- [ ] New feature
- [ ] Breaking change

## Checklist

- [ ] This PR adds or removes a Storybook story.
- [ ] I have added tests to cover my changes.

2022-01-18 21:46 UTC, markacianfrani requested changes
can you nix the changeset por favor?

2022-01-19 14:32 UTC, thomasneal commented
Removed the changeset

2022-01-19 15:43 UTC, markacianfrani commented
> Removed the changeset

I'm still seeing it in there

2022-01-20 17:28 UTC, markacianfrani approved these changes

2022-01-21 16:53 UTC, merged