docs(astro/uxds): fix progress typos
RocketCommunicationsInc/astro pull request #220
Opened 2022-02-01 22:02 UTC by amalyah

## Brief Description

Fixed two typos in the Appearance & Behavior Section. seeconds > seconds. th > the.

## JIRA Link

## Related Issue

## General Notes

## Motivation and Context

## Issues and Limitations

## Types of changes

- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change

## Checklist

- [ ] This PR adds or removes a Storybook story.
- [ ] I have added tests to cover my changes.

2022-02-01 22:55 UTC, micahjones13 requested changes

2022-02-01 22:55 UTC, micahjones13 commented on packages/astro-uxds/_content/components/progress.md
> +An indeterminate progress indicators is displayed as a continuously spinning circle with no strict percentage or timeframe labeled. This type of indicator is usually used when a process takees betwee
Another one here I think. `takees`

2022-02-01 22:55 UTC, micahjones13 commented on packages/astro-uxds/_content/components/progress.md
> +An indeterminate progress indicators is displayed as a continuously spinning circle with no strict percentage or timeframe labeled. This type of indicator is usually used when a process takees betwee
Someone was really 'e' key happy

2022-02-02 14:39 UTC, amalyah commented on packages/astro-uxds/_content/components/progress.md
> +An indeterminate progress indicators is displayed as a continuously spinning circle with no strict percentage or timeframe labeled. This type of indicator is usually used when a process takees betwee
Fixed! Good eye.

2022-02-02 14:52 UTC, amalyah commented
Looks like the commit-lint test failed due to an old commit message "docs(astro-uxds): Updated clock.md in astrouxds (#219)" with a capital letter. @micahjones13 is this something you have the power to work around or should I try to recreate my PR for these fixes?

2022-02-02 16:07 UTC, micahjones13 approved these changes

2022-02-03 13:21 UTC, merged