Astro 3444 clock datein
RocketCommunicationsInc/astro pull request #392
Opened 2022-05-09 18:23 UTC by micahjones13

## Brief Description

Adds a `date-in` prop to rux-clock that allows the user to set the date to be used by clock. 

Adds a snapshot test, storybook story variant as well.

## JIRA Link

https://rocketcom.atlassian.net/browse/ASTRO-3444

## Related Issue
https://github.com/RocketCommunicationsInc/astro/issues/384
## General Notes

Adds additional logic into the _updateTime function if `date-in` is provided. I left my comments in for now to better show my thinking behind it, I will remove them once this get's approved. 

The story is just called `With Date In` but we could call it `With Custom Date` or something. I'm fine either way

## Motivation and Context

Feat request - allow user to choose a date for clock to go by, rather than a date.now() 

## Issues and Limitations

Similar to AOS/LOS, the timestamp works best with the offset provided - if not it still uses the local timezone.

## Types of changes

- [ ] Bug fix
- [x] New feature
- [ ] Breaking change

## Checklist

- [x] This PR adds or removes a Storybook story.
- [x] I have added tests to cover my changes.
- [ ] Regressions are passing and/or failures are documented
- [x] Changes have been checked in evergreen browsers

2022-05-09 18:29 UTC, micahjones13 commented on packages/web-components/src/components/rux-button/readme.md
> -## CSS Custom Properties
I don't know why these got removed? They're still declared in the SCSS file.

2022-05-09 19:00 UTC, markacianfrani requested changes
Can we get this to support a number (milliseconds since whatever, ie Date.now() - 1652122612197)  like the AOS/LOS attr do? 

Might also want to validate an actual date is passed in. with aos/los, its not so bad because it just runs once, but this will throw an error every second.

lookin good tho!

2022-05-09 21:49 UTC, micahjones13 commented on packages/web-components/src/components/rux-clock/rux-clock.tsx
> +            console.warn(
We don't have to do the console warn here, it already will produce a console error. I figured this just tells you exactly what threw the error, but I'm okay with getting rid of it

2022-05-10 15:22 UTC, micahjones13 commented on packages/web-components/src/components/rux-clock/rux-clock.tsx
> +        if (!this.dateIn!.includes('-')) {
I'm not sure if this is the best way to determine if it's a unix date or not. Any better suggestions?

2022-05-12 18:11 UTC, merged