Updated Accordion text for website
RocketCommunicationsInc/astro pull request #692
Opened 2022-09-01 18:45 UTC by ColeStamm

Updated Accordion text for website based on Confluence page

## Brief Description

## JIRA Link

## Related Issue

## General Notes

## Motivation and Context

## Issues and Limitations

## Types of changes

- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change

## Checklist

- [ ] This PR adds or removes a Storybook story.
- [ ] I have added tests to cover my changes.
- [ ] Regressions are passing and/or failures are documented
- [ ] Changes have been checked in evergreen browsers

2022-09-01 19:44 UTC, micahjones13 approved these changes

2022-09-01 19:48 UTC, micahjones13 requested changes
This should go into next, not main. I'll do a main -> next merge tomorrow and then hopefully this PR can just have it's base branch changed.

2022-09-01 19:49 UTC, micahjones13 commented
@markacianfrani unless you think this can just go into main as is. If you do lmk and I'll merge it in

2022-09-06 14:36 UTC, markacianfrani commented
@micahjones13 I think this can go into main. It's just adding additional usage. the part about slots might be a little confusing though given that it's not in code yet. totally your call to make here

2022-09-07 17:46 UTC, micahjones13 approved these changes

2022-09-07 17:46 UTC, merged